#!/bin/bash
# Mon script de post installation desktop Debian 6.0.x
#
# Nicolargo - 08/2120
# GPL
#
# Syntaxe: # su - -c "./debian6postinstall.sh"
# Syntaxe: or # sudo ./debian6postinstall.sh

VERSION="1.00"

#=============================================================================
# Liste des applications installés par le script
# A adapter à vos besoins...
#-----------------------------------------------------------------------------

# Fichier sources.list de référence
SOURCES_LIST="https://raw.githubusercontent.com/jfarcy28/debianpostinstall/master/source.list-debian9?token=AtJ28i49P19UDbfEebUr2eH1QV9WaQtXks5cWV5BwA%3D%3D"

# Ajouter la liste de vos logiciels séparés par des espaces
LISTE=""

# Firefox
LISTE=$LISTE" firefox-esr"

# LibreOffice
LISTE=$LISTE" libreoffice"

# Pilote d'imprimante
LISTE=$LISTE" printer-driver-all"

# Pilote CUP PDF
LISTE=$LISTE" cups-pdf"

#=============================================================================

# Variables globales
#-------------------

APT_GET="apt-get -q -y --force-yes"
WGET="wget -m --no-check-certificate"
DATE=`date +"%Y%m%d%H%M%S"`
LOG_FILE="/tmp/debian6postinstall-$DATE.log"

# Fonctions utilisées par le script
#---------------------------------

displaymessage() {
  echo "$*"
}

displaytitle() {
  displaymessage "------------------------------------------------------------------------------"
  displaymessage "$*"
  displaymessage "------------------------------------------------------------------------------"

}

displayerror() {
  displaymessage "$*" >&2
}

# Premier parametre: ERROR CODE
# Second parametre: MESSAGE
displayerrorandexit() {
  local exitcode=$1
  shift
  displayerror "$*"
  exit $exitcode
}

# Premier parametre: MESSAGE
# Autres parametres: COMMAND
displayandexec() {
  local message=$1
  echo -n "[En cours] $message"
  shift
  echo ">>> $*" >> $LOG_FILE 2>&1
  sh -c "$*" >> $LOG_FILE 2>&1
  local ret=$?
  if [ $ret -ne 0 ]; then
    echo -e "\r\e[0;31m   [ERROR]\e[0m $message"
  else
    echo -e "\r\e[0;32m      [OK]\e[0m $message"
  fi
  return $ret
}

# Debut du programme
#-------------------

# Test que le script est lance en root
if [ $EUID -ne 0 ]; then
  displayerror 1 "Le script doit être lancé en root: # su - -c $0"
fi

# Création du fichier de log
echo "Debut du script" > $LOG_FILE

# Telechargement du fichier sources.list
# Generated by: http://debgen.simplylinux.ch/
# Source: https://raw.github.com/nicolargo/debianpostinstall/master/sources.list-debian6desktop
#----------------------------------------------------------------------------------------------
displaytitle "-- Téléchargement du fichier sources.list
-- $SOURCES_LIST"
displayandexec "Archivage du fichier sources.list actuel" cp /etc/apt/sources.list /etc/apt/sources.list-BACKUP
displayandexec "Téléchargement du nouveau fichier sources.list" $WGET -O /etc/apt/sources.list $SOURCES_LIST

# Mise a jour des depots
#-----------------------

displaytitle "-- Mise à jour du système"

displayandexec "Mise à jour de la liste des dépots" $APT_GET update
displayandexec "Mise à jour des logiciels" $APT_GET upgrade

# Installation des logiciels
#---------------------------

displaytitle "-- Installation des logiciels suivants: $LISTE"

displayandexec "Installation des logiciels" $APT_GET install $LISTE

# Installation de l'imprimante
#------------------

#displaytitle "-- Installation de l'imprimante HP Laserjet CP3525dn"

#displayandexec "Installation de l'imprimante" lpadmin -p 'HPLaserjetCP3525dn' -v 'dnssd://Photosmart%205520%20series._printer._tcp.local/' -P '/usr/share/ppd/hplip/HP/hp-photosmart_5520_series-hpijs.ppd'


echo ""
echo "##############################################################################"
echo ""
echo "                            Fin du script (version $VERSION)"
echo ""
echo " Le log du script se trouve dans le fichier:"
echo "    $LOG_FILE"
echo ""
echo "##############################################################################"
echo ""

echo "Fin du script" >> $LOG_FILE

# The end...
############